import { NextResponse } from 'next/server';

export function verifyAuth(request: Request): NextResponse | null {
  const authHeader = request.headers.get('Authorization');
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const token = authHeader.split(' ')[1];

  // We only check if the token is present (random token generated by /api/auth/token)
  if (!token) {
    return NextResponse.json({ error: 'Invalid Token Format' }, { status: 401 });
  }

  return null;
}
